### YamlMime:ManagedReference
items:
- uid: Noname.Application.ValueObjects.PlayerLevelUpEvent
  commentId: T:Noname.Application.ValueObjects.PlayerLevelUpEvent
  id: PlayerLevelUpEvent
  parent: Noname.Application.ValueObjects
  children:
  - Noname.Application.ValueObjects.PlayerLevelUpEvent.#ctor(System.Int32,System.Single,System.Single)
  - Noname.Application.ValueObjects.PlayerLevelUpEvent.CurrentExperience
  - Noname.Application.ValueObjects.PlayerLevelUpEvent.ExperienceForNextLevel
  - Noname.Application.ValueObjects.PlayerLevelUpEvent.Level
  langs:
  - csharp
  - vb
  name: PlayerLevelUpEvent
  nameWithType: PlayerLevelUpEvent
  fullName: Noname.Application.ValueObjects.PlayerLevelUpEvent
  type: Struct
  assemblies:
  - Assembly-CSharp
  namespace: Noname.Application.ValueObjects
  summary: 플레이어가 레벨업했을 때 발생하는 이벤트입니다.
  example: []
  syntax:
    content: public readonly struct PlayerLevelUpEvent
    content.vb: Public Structure PlayerLevelUpEvent
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.GetType
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: Noname.Application.ValueObjects.PlayerLevelUpEvent.#ctor(System.Int32,System.Single,System.Single)
  commentId: M:Noname.Application.ValueObjects.PlayerLevelUpEvent.#ctor(System.Int32,System.Single,System.Single)
  id: '#ctor(System.Int32,System.Single,System.Single)'
  parent: Noname.Application.ValueObjects.PlayerLevelUpEvent
  langs:
  - csharp
  - vb
  name: PlayerLevelUpEvent(int, float, float)
  nameWithType: PlayerLevelUpEvent.PlayerLevelUpEvent(int, float, float)
  fullName: Noname.Application.ValueObjects.PlayerLevelUpEvent.PlayerLevelUpEvent(int, float, float)
  type: Constructor
  assemblies:
  - Assembly-CSharp
  namespace: Noname.Application.ValueObjects
  syntax:
    content: public PlayerLevelUpEvent(int level, float currentExperience, float experienceForNextLevel)
    parameters:
    - id: level
      type: System.Int32
    - id: currentExperience
      type: System.Single
    - id: experienceForNextLevel
      type: System.Single
    content.vb: Public Sub New(level As Integer, currentExperience As Single, experienceForNextLevel As Single)
  overload: Noname.Application.ValueObjects.PlayerLevelUpEvent.#ctor*
  nameWithType.vb: PlayerLevelUpEvent.New(Integer, Single, Single)
  fullName.vb: Noname.Application.ValueObjects.PlayerLevelUpEvent.New(Integer, Single, Single)
  name.vb: New(Integer, Single, Single)
- uid: Noname.Application.ValueObjects.PlayerLevelUpEvent.Level
  commentId: P:Noname.Application.ValueObjects.PlayerLevelUpEvent.Level
  id: Level
  parent: Noname.Application.ValueObjects.PlayerLevelUpEvent
  langs:
  - csharp
  - vb
  name: Level
  nameWithType: PlayerLevelUpEvent.Level
  fullName: Noname.Application.ValueObjects.PlayerLevelUpEvent.Level
  type: Property
  assemblies:
  - Assembly-CSharp
  namespace: Noname.Application.ValueObjects
  summary: 레벨업 후 현재 레벨.
  example: []
  syntax:
    content: public int Level { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public ReadOnly Property Level As Integer
  overload: Noname.Application.ValueObjects.PlayerLevelUpEvent.Level*
- uid: Noname.Application.ValueObjects.PlayerLevelUpEvent.CurrentExperience
  commentId: P:Noname.Application.ValueObjects.PlayerLevelUpEvent.CurrentExperience
  id: CurrentExperience
  parent: Noname.Application.ValueObjects.PlayerLevelUpEvent
  langs:
  - csharp
  - vb
  name: CurrentExperience
  nameWithType: PlayerLevelUpEvent.CurrentExperience
  fullName: Noname.Application.ValueObjects.PlayerLevelUpEvent.CurrentExperience
  type: Property
  assemblies:
  - Assembly-CSharp
  namespace: Noname.Application.ValueObjects
  summary: 누적 경험치.
  example: []
  syntax:
    content: public float CurrentExperience { get; }
    parameters: []
    return:
      type: System.Single
    content.vb: Public ReadOnly Property CurrentExperience As Single
  overload: Noname.Application.ValueObjects.PlayerLevelUpEvent.CurrentExperience*
- uid: Noname.Application.ValueObjects.PlayerLevelUpEvent.ExperienceForNextLevel
  commentId: P:Noname.Application.ValueObjects.PlayerLevelUpEvent.ExperienceForNextLevel
  id: ExperienceForNextLevel
  parent: Noname.Application.ValueObjects.PlayerLevelUpEvent
  langs:
  - csharp
  - vb
  name: ExperienceForNextLevel
  nameWithType: PlayerLevelUpEvent.ExperienceForNextLevel
  fullName: Noname.Application.ValueObjects.PlayerLevelUpEvent.ExperienceForNextLevel
  type: Property
  assemblies:
  - Assembly-CSharp
  namespace: Noname.Application.ValueObjects
  summary: 다음 레벨까지 필요한 경험치.
  example: []
  syntax:
    content: public float ExperienceForNextLevel { get; }
    parameters: []
    return:
      type: System.Single
    content.vb: Public ReadOnly Property ExperienceForNextLevel As Single
  overload: Noname.Application.ValueObjects.PlayerLevelUpEvent.ExperienceForNextLevel*
references:
- uid: Noname.Application.ValueObjects
  commentId: N:Noname.Application.ValueObjects
  isExternal: true
  href: Noname.html
  name: Noname.Application.ValueObjects
  nameWithType: Noname.Application.ValueObjects
  fullName: Noname.Application.ValueObjects
  spec.csharp:
  - uid: Noname
    name: Noname
    isExternal: true
    href: Noname.html
  - name: .
  - uid: Noname.Application
    name: Application
    isExternal: true
    href: Noname.Application.html
  - name: .
  - uid: Noname.Application.ValueObjects
    name: ValueObjects
    isExternal: true
    href: Noname.Application.ValueObjects.html
  spec.vb:
  - uid: Noname
    name: Noname
    isExternal: true
    href: Noname.html
  - name: .
  - uid: Noname.Application
    name: Application
    isExternal: true
    href: Noname.Application.html
  - name: .
  - uid: Noname.Application.ValueObjects
    name: ValueObjects
    isExternal: true
    href: Noname.Application.ValueObjects.html
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Noname.Application.ValueObjects.PlayerLevelUpEvent.#ctor*
  commentId: Overload:Noname.Application.ValueObjects.PlayerLevelUpEvent.#ctor
  isExternal: true
  href: Noname.Application.ValueObjects.PlayerLevelUpEvent.html#Noname_Application_ValueObjects_PlayerLevelUpEvent__ctor_System_Int32_System_Single_System_Single_
  name: PlayerLevelUpEvent
  nameWithType: PlayerLevelUpEvent.PlayerLevelUpEvent
  fullName: Noname.Application.ValueObjects.PlayerLevelUpEvent.PlayerLevelUpEvent
  nameWithType.vb: PlayerLevelUpEvent.New
  fullName.vb: Noname.Application.ValueObjects.PlayerLevelUpEvent.New
  name.vb: New
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.single
  name: float
  nameWithType: float
  fullName: float
  nameWithType.vb: Single
  fullName.vb: Single
  name.vb: Single
- uid: Noname.Application.ValueObjects.PlayerLevelUpEvent.Level*
  commentId: Overload:Noname.Application.ValueObjects.PlayerLevelUpEvent.Level
  isExternal: true
  href: Noname.Application.ValueObjects.PlayerLevelUpEvent.html#Noname_Application_ValueObjects_PlayerLevelUpEvent_Level
  name: Level
  nameWithType: PlayerLevelUpEvent.Level
  fullName: Noname.Application.ValueObjects.PlayerLevelUpEvent.Level
- uid: Noname.Application.ValueObjects.PlayerLevelUpEvent.CurrentExperience*
  commentId: Overload:Noname.Application.ValueObjects.PlayerLevelUpEvent.CurrentExperience
  isExternal: true
  href: Noname.Application.ValueObjects.PlayerLevelUpEvent.html#Noname_Application_ValueObjects_PlayerLevelUpEvent_CurrentExperience
  name: CurrentExperience
  nameWithType: PlayerLevelUpEvent.CurrentExperience
  fullName: Noname.Application.ValueObjects.PlayerLevelUpEvent.CurrentExperience
- uid: Noname.Application.ValueObjects.PlayerLevelUpEvent.ExperienceForNextLevel*
  commentId: Overload:Noname.Application.ValueObjects.PlayerLevelUpEvent.ExperienceForNextLevel
  isExternal: true
  href: Noname.Application.ValueObjects.PlayerLevelUpEvent.html#Noname_Application_ValueObjects_PlayerLevelUpEvent_ExperienceForNextLevel
  name: ExperienceForNextLevel
  nameWithType: PlayerLevelUpEvent.ExperienceForNextLevel
  fullName: Noname.Application.ValueObjects.PlayerLevelUpEvent.ExperienceForNextLevel
