### YamlMime:ManagedReference
items:
- uid: Noname.Application.UseCases.StartGameUseCase
  commentId: T:Noname.Application.UseCases.StartGameUseCase
  id: StartGameUseCase
  parent: Noname.Application.UseCases
  children:
  - Noname.Application.UseCases.StartGameUseCase.#ctor(Noname.Application.Ports.IGameStateRepository)
  - Noname.Application.UseCases.StartGameUseCase.Execute
  langs:
  - csharp
  - vb
  name: StartGameUseCase
  nameWithType: StartGameUseCase
  fullName: Noname.Application.UseCases.StartGameUseCase
  type: Class
  assemblies:
  - Assembly-CSharp
  namespace: Noname.Application.UseCases
  summary: 게임 상태를 초기화하여 새 세션을 시작하는 유즈케이스입니다.
  example: []
  syntax:
    content: public sealed class StartGameUseCase
    content.vb: Public NotInheritable Class StartGameUseCase
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.GetType
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
- uid: Noname.Application.UseCases.StartGameUseCase.#ctor(Noname.Application.Ports.IGameStateRepository)
  commentId: M:Noname.Application.UseCases.StartGameUseCase.#ctor(Noname.Application.Ports.IGameStateRepository)
  id: '#ctor(Noname.Application.Ports.IGameStateRepository)'
  parent: Noname.Application.UseCases.StartGameUseCase
  langs:
  - csharp
  - vb
  name: StartGameUseCase(IGameStateRepository)
  nameWithType: StartGameUseCase.StartGameUseCase(IGameStateRepository)
  fullName: Noname.Application.UseCases.StartGameUseCase.StartGameUseCase(Noname.Application.Ports.IGameStateRepository)
  type: Constructor
  assemblies:
  - Assembly-CSharp
  namespace: Noname.Application.UseCases
  syntax:
    content: public StartGameUseCase(IGameStateRepository repository)
    parameters:
    - id: repository
      type: Noname.Application.Ports.IGameStateRepository
    content.vb: Public Sub New(repository As IGameStateRepository)
  overload: Noname.Application.UseCases.StartGameUseCase.#ctor*
  nameWithType.vb: StartGameUseCase.New(IGameStateRepository)
  fullName.vb: Noname.Application.UseCases.StartGameUseCase.New(Noname.Application.Ports.IGameStateRepository)
  name.vb: New(IGameStateRepository)
- uid: Noname.Application.UseCases.StartGameUseCase.Execute
  commentId: M:Noname.Application.UseCases.StartGameUseCase.Execute
  id: Execute
  parent: Noname.Application.UseCases.StartGameUseCase
  langs:
  - csharp
  - vb
  name: Execute()
  nameWithType: StartGameUseCase.Execute()
  fullName: Noname.Application.UseCases.StartGameUseCase.Execute()
  type: Method
  assemblies:
  - Assembly-CSharp
  namespace: Noname.Application.UseCases
  summary: 현재 GameState를 초기화합니다.
  example: []
  syntax:
    content: public void Execute()
    content.vb: Public Sub Execute()
  overload: Noname.Application.UseCases.StartGameUseCase.Execute*
references:
- uid: Noname.Application.UseCases
  commentId: N:Noname.Application.UseCases
  isExternal: true
  href: Noname.html
  name: Noname.Application.UseCases
  nameWithType: Noname.Application.UseCases
  fullName: Noname.Application.UseCases
  spec.csharp:
  - uid: Noname
    name: Noname
    isExternal: true
    href: Noname.html
  - name: .
  - uid: Noname.Application
    name: Application
    isExternal: true
    href: Noname.Application.html
  - name: .
  - uid: Noname.Application.UseCases
    name: UseCases
    isExternal: true
    href: Noname.Application.UseCases.html
  spec.vb:
  - uid: Noname
    name: Noname
    isExternal: true
    href: Noname.html
  - name: .
  - uid: Noname.Application
    name: Application
    isExternal: true
    href: Noname.Application.html
  - name: .
  - uid: Noname.Application.UseCases
    name: UseCases
    isExternal: true
    href: Noname.Application.UseCases.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Noname.Application.UseCases.StartGameUseCase.#ctor*
  commentId: Overload:Noname.Application.UseCases.StartGameUseCase.#ctor
  isExternal: true
  href: Noname.Application.UseCases.StartGameUseCase.html#Noname_Application_UseCases_StartGameUseCase__ctor_Noname_Application_Ports_IGameStateRepository_
  name: StartGameUseCase
  nameWithType: StartGameUseCase.StartGameUseCase
  fullName: Noname.Application.UseCases.StartGameUseCase.StartGameUseCase
  nameWithType.vb: StartGameUseCase.New
  fullName.vb: Noname.Application.UseCases.StartGameUseCase.New
  name.vb: New
- uid: Noname.Application.Ports.IGameStateRepository
  commentId: T:Noname.Application.Ports.IGameStateRepository
  parent: Noname.Application.Ports
  isExternal: true
  href: Noname.Application.Ports.IGameStateRepository.html
  name: IGameStateRepository
  nameWithType: IGameStateRepository
  fullName: Noname.Application.Ports.IGameStateRepository
- uid: Noname.Application.Ports
  commentId: N:Noname.Application.Ports
  isExternal: true
  href: Noname.html
  name: Noname.Application.Ports
  nameWithType: Noname.Application.Ports
  fullName: Noname.Application.Ports
  spec.csharp:
  - uid: Noname
    name: Noname
    isExternal: true
    href: Noname.html
  - name: .
  - uid: Noname.Application
    name: Application
    isExternal: true
    href: Noname.Application.html
  - name: .
  - uid: Noname.Application.Ports
    name: Ports
    isExternal: true
    href: Noname.Application.Ports.html
  spec.vb:
  - uid: Noname
    name: Noname
    isExternal: true
    href: Noname.html
  - name: .
  - uid: Noname.Application
    name: Application
    isExternal: true
    href: Noname.Application.html
  - name: .
  - uid: Noname.Application.Ports
    name: Ports
    isExternal: true
    href: Noname.Application.Ports.html
- uid: Noname.Application.UseCases.StartGameUseCase.Execute*
  commentId: Overload:Noname.Application.UseCases.StartGameUseCase.Execute
  isExternal: true
  href: Noname.Application.UseCases.StartGameUseCase.html#Noname_Application_UseCases_StartGameUseCase_Execute
  name: Execute
  nameWithType: StartGameUseCase.Execute
  fullName: Noname.Application.UseCases.StartGameUseCase.Execute
