name: Deploy DocFX Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Install DocFX
        run: dotnet tool install -g docfx
        shell: pwsh

      - name: Add dotnet tools to PATH
        run: echo "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh

      - name: Prepare DocFX artifacts
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process
          ./PrepareDocfx.ps1

      - name: Generate DocFX metadata
        run: docfx metadata

      - name: Build DocFX site
        run: docfx build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
